version: '2'

services:
  drone-server:
    container_name: drone-server
    image: drone/drone:2
    volumes:
      - ./:/data
    restart: always
    labels:
      - traefik.http.routers.drone-server.rule=Host(`drone.local.com`) # use traefik load balancer to forward the port
    environment:
      - TZ=Asia/Taipei
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}

      - DRONE_LOGS_TRACE=true
      - DRONE_LOGS_PRETTY=true
      - DRONE_LOGS_COLOR=true

      - DRONE_RUNNER_CAPACITY=10
    networks:
      - web_service
networks:
  web_service:
    external: true
